"""JSONL session audit log — format specification.

Every line is a self-contained UTF-8 JSON object with no embedded newlines.
Lines are written in strict chronological order; the seq field gives a 1-based
integer that is unique and monotonically increasing within each file.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FILE NAMING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Files are named <YYYYMMDD>T<HHMMSS>.jsonl, where the timestamp is the UTC
  session-start time with second precision (e.g. "20260309T213300.jsonl").
  Each session produces exactly one file.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COMMON ENVELOPE  (first three fields on every record, in this order)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  "seq"      integer  1-based counter, unique within the file.
  "ts"       string   ISO-8601 UTC timestamp with microsecond precision and
                      explicit UTC offset, e.g. "2026-03-09T21:33:14.316408+00:00".
                      Generated by the logger at write time.
  "category" string   Discriminator for the record shape. Exactly one of:
                        "protocol"   "wire_rx"   "model_rx"
                        "model_tx"   "lifecycle"

  All category-specific fields follow these three.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CATEGORY "protocol"  — every message that crosses the host ↔ modelrelay boundary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  "direction"   string   "inbound"       (host → modelrelay)
                         "outbound"      (modelrelay → host)
                         "inbound_error" (see below)
  "disposition" string   Outcome of modelrelay's attempt to handle this message.
                         Exactly one of:
                           "processed"  — message was accepted and caused a state
                                          change or action. All inbound messages
                                          that clear the KNOWN_INBOUND_TYPES gate
                                          are processed: cmd.* messages are
                                          dispatched to a registered handler, and
                                          tool.*_response messages resolve a
                                          pending future. All outbound messages
                                          are sent deliberately and are processed.
                           "erroneous"  — the inbound line was rejected before
                                          any processing could occur: either JSON
                                          could not be parsed or the type is
                                          unknown to modelrelay.
                         There is no "ignored" value for protocol records: the
                         protocol layer has no informational pass-through — every
                         accepted message causes an action and every unknown
                         message is rejected as an error.
  "msg_id"      string   UUID from the LOJP envelope "id" field.
  "msg_ts"      string   Timestamp from the LOJP envelope "ts" field. Uses the
                         wire format: ISO-8601 UTC with "Z" suffix and millisecond
                         precision, e.g. "2026-03-09T21:33:14.316Z".
                         May be an empty string if the envelope omitted this field.
  "msg_type"    string   LOJP message type, e.g. "cmd.prompt", "status.activity",
                         "model.text_delta", "status.usage", "status.session_ended".
  "payload"     object   The "payload" field from the LOJP envelope, verbatim.
                         Shape depends on msg_type; see stdio/protocol.py.

  Note: the LOJP protocol version field ("lojp") is not logged; it carries no
  per-message information and is defined at the protocol level, not per record.

  When an inbound line is rejected (JSON parse failure or unknown message type)
  the record uses direction "inbound_error" and disposition "erroneous".
  Additional fields replace msg_id / msg_ts / msg_type / payload:
    "raw"    string  — the raw text of the offending line (or best-effort decode)
    "reason" string  — "PARSE_ERROR" or "UNKNOWN_TYPE"
    "detail" string  — the error message or the unrecognised type string

  Example (inbound, processed):
    {"seq":1, "ts":"2026-03-09T21:33:14.316408+00:00", "category":"protocol",
     "direction":"inbound", "disposition":"processed",
     "msg_id":"5c98…", "msg_ts":"2026-03-09T21:33:14.316Z",
     "msg_type":"cmd.prompt", "payload":{"text":"fix the bug"}}

  Example (outbound, processed):
    {"seq":2, "ts":"2026-03-09T21:33:14.317012+00:00", "category":"protocol",
     "direction":"outbound", "disposition":"processed",
     "msg_id":"a3b1…", "msg_ts":"2026-03-09T21:33:14.317Z",
     "msg_type":"status.activity",
     "payload":{"state":"generating","description":"Generating\u2026"}}

  Example (inbound_error, erroneous — parse failure):
    {"seq":3, "ts":"…", "category":"protocol",
     "direction":"inbound_error", "disposition":"erroneous",
     "raw":"not valid json", "reason":"PARSE_ERROR",
     "detail":"Expecting value: line 1 column 1 (char 0)"}

  Example (inbound_error, erroneous — unknown type):
    {"seq":4, "ts":"…", "category":"protocol",
     "direction":"inbound_error", "disposition":"erroneous",
     "raw":"{\"lojp\":\"1.0\",\"type\":\"bogus.msg\",…}", "reason":"UNKNOWN_TYPE",
     "detail":"bogus.msg"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CATEGORY "wire_rx"  — every raw frame received from the backend, before filtering
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  "backend"      string   "anthropic"       — one parsed SSE data payload
                          "openai-realtime" — one parsed WebSocket message body
  "disposition"  string   Outcome of modelrelay's attempt to handle this frame.
                          Exactly one of:
                            "processed"  — frame type was recognised and caused a
                                           state change or BackendEvent emission
                            "ignored"    — frame was well-formed but no handler
                                           fired; includes both known informational
                                           frames (e.g. "session.created",
                                           "conversation.item.created") and any
                                           unrecognised type that falls through
                                           the dispatch chain
                            "erroneous"  — raw bytes could not be parsed as JSON;
                                           "frame_raw" and "error" are present
                                           instead of "frame"
  "frame"        object   The complete parsed JSON as received on the wire.
                          Present on processed and ignored records.
  "frame_raw"    string   The raw text of the unparseable payload.
                          Present on erroneous records instead of "frame".
  "error"        string   JSON decode error message.
                          Present on erroneous records.

  Example (Anthropic, processed):
    {"seq":3, "ts":"…", "category":"wire_rx", "backend":"anthropic",
     "disposition":"processed",
     "frame":{"type":"content_block_delta",
              "delta":{"type":"text_delta","text":"Hello"}}}

  Example (OpenAI Realtime, ignored):
    {"seq":4, "ts":"…", "category":"wire_rx", "backend":"openai-realtime",
     "disposition":"ignored",
     "frame":{"type":"conversation.item.created","item":{"id":"item_1",…}}}

  Example (erroneous):
    {"seq":5, "ts":"…", "category":"wire_rx", "backend":"openai-realtime",
     "disposition":"erroneous",
     "frame_raw":"not valid json{{{", "error":"Expecting value: line 1 column 1"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CATEGORY "model_rx"  — BackendEvent emitted by the backend to the orchestrator
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  "event"  string   One of the following event type names (uppercase).
  "data"   object   Event-specific fields as listed below.

  event         data fields
  ──────────    ──────────────────────────────────────────────────────────────
  CONNECTED     model (string) — backend-reported model identifier
  TEXT_DELTA    text (string)  — one streamed text chunk
  TOOL_CALL     call_id (string), name (string), args (object)
  TURN_DONE     input_tokens (integer), output_tokens (integer)
  RATE_LIMITED  retry_after_s (number|null) — seconds until quota resets
  ERROR         message (string), fatal (boolean)
  DISCONNECTED  (empty object) — WebSocket lost; reconnect in progress

  Example:
    {"seq":5, "ts":"…", "category":"model_rx",
     "event":"TOOL_CALL",
     "data":{"call_id":"c1","name":"read","args":{"resource":"f.py"}}}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CATEGORY "model_tx"  — message sent from the orchestrator to the backend
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  "kind"   string   Discriminator. Additional fields are inlined alongside "kind"
                    (not nested). Exactly one of:

  kind            additional fields
  ─────────────   ─────────────────────────────────────────────────────────────
  "send_turn"     text (string)  — the full user prompt text
  "tool_result"   call_id (string), name (string), args (object),
                  result (string) — tool output returned to the model
  "inject_note"   text (string)  — system note injected into context

  Example (send_turn):
    {"seq":6, "ts":"…", "category":"model_tx",
     "kind":"send_turn", "text":"fix the bug"}

  Example (tool_result):
    {"seq":7, "ts":"…", "category":"model_tx",
     "kind":"tool_result", "call_id":"c1", "name":"read",
     "args":{"resource":"f.py"}, "result":"1: import sys\\n2: …"}

  Example (inject_note):
    {"seq":8, "ts":"…", "category":"model_tx",
     "kind":"inject_note", "text":"'f.py' changed externally."}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CATEGORY "lifecycle"  — session-level events emitted by modelrelay itself
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  "event"  string   Name of the lifecycle event.
  "data"   object   Event-specific fields as listed below.

  event            data fields
  ──────────────   ─────────────────────────────────────────────────────────
  session_start    backend (string), model (string), log_file (string)
  session_end      total_tokens (integer), cost_usd (number)

  session_start is always the first record in the file (seq=1).
  session_end is always the last record in the file.

  Example:
    {"seq":1, "ts":"…", "category":"lifecycle",
     "event":"session_start",
     "data":{"backend":"anthropic","model":"claude-opus-4-5",
             "log_file":"20260309T213300.jsonl"}}
"""
from __future__ import annotations

import json
import os
import threading
from datetime import datetime, timezone


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class Logger:
    def __init__(self, log_dir: str, session_start: datetime | None = None):
        os.makedirs(log_dir, exist_ok=True)
        start = session_start or datetime.now(timezone.utc)
        fname = start.strftime("%Y%m%dT%H%M%S") + ".jsonl"
        self._path = os.path.join(log_dir, fname)
        self._seq  = 0
        self._lock = threading.Lock()
        try:
            self._f = open(self._path, "w", buffering=1, encoding="utf-8")
            self._closed = False
        except Exception:
            self._f = None
            self._closed = True

    @property
    def path(self) -> str:
        return self._path

    def _write(self, category: str, fields: dict):
        """Write one record: seq, ts, category come first, then category fields."""
        if self._closed or self._f is None:
            return
        with self._lock:
            self._seq += 1
            record = {"seq": self._seq, "ts": _now(), "category": category, **fields}
            line = json.dumps(record, ensure_ascii=False, default=str)
            self._f.write(line + "\n")

    # ── public API ────────────────────────────────────────────────────────────

    def log_protocol(self, envelope: dict, direction: str):
        """Log a host ↔ modelrelay message (category: protocol).

        All messages reaching this method have cleared the KNOWN_INBOUND_TYPES
        gate (inbound) or were sent deliberately by modelrelay (outbound), so
        disposition is always "processed".
        """
        self._write("protocol", {
            "direction":   direction,
            "disposition": "processed",
            "msg_id":    envelope.get("id", ""),
            "msg_ts":    envelope.get("ts", ""),
            "msg_type":  envelope.get("type", ""),
            "payload":   envelope.get("payload", {}),
        })

    def log_wire_rx(self, backend: str, frame: dict, disposition: str):
        """Log a raw wire frame from the backend (category: wire_rx).

        disposition must be "processed" (frame caused state change or BackendEvent)
        or "ignored" (well-formed but no handler fired).
        """
        self._write("wire_rx", {
            "backend":     backend,
            "disposition": disposition,
            "frame":       frame,
        })

    def log_wire_rx_error(self, backend: str, raw: str, error: str):
        """Log an unparseable raw frame from the backend (category: wire_rx).
        disposition is always "erroneous"; uses frame_raw instead of frame."""
        self._write("wire_rx", {
            "backend":     backend,
            "disposition": "erroneous",
            "frame_raw":   raw,
            "error":       error,
        })

    def log_protocol_inbound_error(self, raw: str, reason: str, detail: str):
        """Log a rejected inbound line (category: protocol, direction: inbound_error).

        disposition is always "erroneous": the line was rejected before any
        processing could occur.
        """
        self._write("protocol", {
            "direction":   "inbound_error",
            "disposition": "erroneous",
            "raw":         raw,
            "reason":      reason,
            "detail":      detail,
        })

    def log_model_rx(self, event_type: str, data: dict):
        """Log a BackendEvent emitted toward the orchestrator (category: model_rx)."""
        self._write("model_rx", {
            "event": event_type,
            "data":  data,
        })

    def log_model_tx(self, kind: str, **fields):
        """Log a message sent to the backend (category: model_tx)."""
        self._write("model_tx", {"kind": kind, **fields})

    def write_event(self, event: str, data: dict):
        """Log a session lifecycle event (category: lifecycle)."""
        self._write("lifecycle", {"event": event, "data": data})

    def close(self):
        if not self._closed and self._f:
            self._closed = True
            self._f.close()
